# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adb569bcec35df9b36156c03d1768270706f841a4b7613e98f35af8f8a845a6b5acb32adde5990358c9e9c2340029a0330089059925bb04e38df447f0db76641

test:
  secret_key_base: a2cc6370411b7a18074013719b69e59d7406a37ba7d21af8507508224462f2077cb1097faaafe4f3f2fc7d4b768684647a068ec32de83e477e115552523bb574

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
